env: "local"
token_options:
  token_refresh_ttl: 200h
  token_access_ttl: 30m
  token_verification_ttl: 24h
redis:
  redis_host: "redis"
  redis_port: 6379
  redis_password: "FGEW%%^22566gGege"
mailersend_api_key: "f"
jwt_secret: "dsdfwfwrErfg5rujnns"
hcaptcha_secret: "dfgheyklokmbbv"
auth:
  host: "localhost"
  port: 44044
  timeout: 5s
grpc:
  port: 44043
  timeout: 5s

